"""Initial Migration

Revision ID: 66a6f950e0b5
Revises: 
Create Date: 2020-09-28 23:36:09.677392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a6f950e0b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_user_id_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'users', ['users_id'], ['id'])
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_user_id_fkey', 'pitch', 'users', ['user_id'], ['id'])
    op.drop_column('pitch', 'users_id')
    # ### end Alembic commands ###
